### PR TITLE
Add USize, ISize issue #34

### PR DESCRIPTION
**Pull request by rurban**

### CODE REVIEW

**Comment by andymcn** [comment]
Can you also add ULong and ILong please.

**Comment by rurban** [comment]
Sure. 

Are there no type aliases for Int, UInt or Float/Double btw? I find them very convenient in my type system.

**Comment by andymcn** [comment]
No we don't have aliases for those. We're very much against numeric types whose size is not explicit as this leads to loads of bugs when code is ported to platforms with different sizes.

Originally all the Pony numeric types had explicit sizes, but we added the size and long ones because they're needed for writing cross platform code. However, we recommend that they're only used when absolutely needed and we won't be adding any more variable size types unless we have to.

Note that the size and long types are not just aliases for some other integer types, they are actually different types, and explicit conversions to/from the fixed size types are needed. This approach is needed to avoid the problems C has with variable size types.

For Int and UInt use the size you actually want.

F32 is exactly C float and F64 is exactly C double, so there's no need for aliases anyway.

**Comment by rurban** [comment]
I thought not of Int or Float type-alias for an API, you are right. This is wrong. I made the same mistake, bad C habits, perl6 just fixed that.
I thought just for convenience in the matcher, e.g.

    match x
    | let i :Int => "Int"

instead of listing all Int types there.

**Comment by andymcn** [comment]
Sorry, I misunderstood what you were asking there. We do have union types defined that may be helpful to you. The following are defined in `builtin/arithmetic.pony`:
```pony
type Number is (Signed | Unsigned | Float)
type Signed is (I8 | I16 | I32 | I64 | I128 | ILong | ISize)
type Unsigned is (U8 | U16 | U32 | U64 | U128 | ULong | USize)
type Float is (F32 | F64)
```

So you can do:
```pony
match x
| let i: Signed => ...
end
```

**Pull request merged**
