### PR TITLE
Document the basic use of delegates in pony

### PR DESCRIPTION
**Pull request by darach**
Add some basic documentation on the use of delegates.

@sylvanc @andymcn Let me know if I got anything wrong and/or need to tweak anything

### CODE REVIEW

**Comment by sylvanc** [comment]
Nice!

**Comment by andymcn** [comment]
Thanks for the docs. However, the line
```
let w : SimpleWombat delegate Wombat = KungFuWombat
```
is an error, since `SimpleWombat` and `KungFuWombat` are both classes and so not subtypes of each other.

Any chance you could check that all your other examples actually compile?

**Comment by darach** [comment]
@andymcn Well spotted. Somehow I missed this copying between ST and the doc. PR to follow to resolve.

**Comment by andymcn** [comment]
Having reread this I have a further change request. It occurs to me that you haven't actually explained what delegation **is**. You've said it's like mixins, which great for people who are used to languages that have mixins, but we'd like to accessible to programmers from as many backgrounds as possible. In particular, some languages use the word delegate to mean slightly different things. (In C# it's effectively a function pointer, seriously, they called that a delegate!)

You say "The actor `Main` delegates its __Wombat__ness to the `SimpleWombat` class" which is a good start (and bonus points for the word wombatness). Could we expand upon that slightly? Something along the lines of "whenever a method in the `Wombat` trait is called on `Main` that call is redirected to the `SimpleWombat` stored in the `w` field" maybe?

**Comment by darach** [comment]
@andymcn Agreed. I'll update later today, opportunity permitting.

**Pull request merged**
